apiVersion: v1
kind: Service
metadata:
  name: opendkim
  namespace: mail
spec:
  selector:
    app: opendkim
  ports:
  - name: opendkim
    port: 8892
    protocol: TCP
    targetPort: 8892
  type: ClusterIP
