apiVersion: v1
kind: ConfigMap
metadata:
  name: spamass
  namespace: mail
data:
  spamassassin: |
    SAHOME="/var/lib/spamassassin"
    SAGLOBALCFGPATH="/etc/spamassassin"
    
    # Change to one to enable spamd
    ENABLED=1
    
    # Options
    # See man spamd for possible options. The -d option is automatically added.
    OPTIONS="-x --max-children 5 -A 10. --helper-home-dir ${SAHOME} -u spamd -g spamd --siteconfigpath ${SAGLOBALCFGPATH} --socketpath=/var/run/spamd.sock --socketowner=spamd --socketgroup=spamd --socketmode=0660 -s /var/log/spamd.log"
    
    # Pid file
    # Where should spamd write its PID to file? If you use the -u or
    # --username option above, this needs to be writable by that user.
    # Otherwise, the init script will not be able to shut spamd down.
    PIDFILE="/var/run/spamd.pid"
    
    # Cronjob
    # Set to anything but 0 to enable the cron job to automatically update
    # spamassassin's rules on a nightly basis
    CRON=1
  spamass-milter: |
    SOCKET="inet:783@0.0.0.0"
    OPTIONS="-u spamass-milter -i 127.0.0.1 -m -I -- --socket=/var/run/spamd.sock"
