apiVersion: v1
kind: Service
metadata:
  name: spamass
  namespace: mail
spec:
  selector:
    app: spamass
  ports:
  - name: spamass
    port: 783
    protocol: TCP
    targetPort: 783
  type: ClusterIP
